language: python

matrix:
  include:
    - name: "python 3.5 on xenial Linux"
      python: 3.5
      dist: xenial
      sudo: true
    - name: "python 3.7 on xenial Linux"
      python: 3.7
      dist: xenial
      sudo: true
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      before_install: choco install python3
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install .
  - pip3 install coveralls

# command to run tests
script:
  - nosetests --with-doctest --with-coverage -c nose.cfg

after_success:
- coveralls

